services:
  redis:
    image: redis:7.4
    container_name: redis_server
    networks:
      - kuchak_net
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        
  postgres:
    image: postgres:17-alpine3.20
    container_name: postgres_db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_APP_USER: ${DB_APP_USER}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    networks:
      - kuchak_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_APP_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
 

volumes:
  postgres_data:

networks:
  kuchak_net:
    name: kuchak_net
    driver: bridge
